### PR TITLE
 add shapefile error cases

### PR DESCRIPTION
**Pull request by mtCarto**

### CODE REVIEW

**Comment by tetriscode** [comment]
Lets stick to a convention of `<PROCESSOR>_<TYPE>_<MESSAGE>_ERROR` for errors which in this case will be `SIO_SHP_SOMEERRORTITLE_ERROR`

**Comment by joshkendrick** [comment]
@tetriscode which ones? `MISSING_PROJECTION_ERROR` and `SHP_MISMATCHED_GEOMETERY_TYPE_ERROR`

**Comment by emerkle826** [comment]
I'm fine with the convention, though we probably need to only enforce it on new events/actions going forward as retro fitting existing events/actions will be too disruptive for others.

**Comment by emerkle826** [comment]
I've pulled this change into #37

**Pull request closed without merging**
